import { Category, AppLanguage } from './enums';

export const TRANSLATIONS = {
  ar: {
    appName: 'SYRIA GAMING HUB',
    home: 'الرئيسية',
    shop: 'المتجر',
    categories: 'التصنيفات',
    support: 'الدعم الفني',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    heroTitle: 'عالمك الرقمي في مكان واحد',
    heroSubtitle: '',
    instantDelivery: 'تسليم فوري',
    featuredProducts: 'منتجات مميزة',
    bestSellers: 'الأكثر مبيعاً',
    browseAll: 'تصفح الكل',
    steamAccounts: 'حسابات ستيم',
    steamCodes: 'أكواد ستيم',
    discordNitro: 'ديسكورد نيترو',
    digitalGames: 'ألعاب رقمية',
    safetyFirst: 'الأمان أولاً',
    trustedMarketplace: 'منصة موثوقة لجميع احتياجاتك.',
    cart: 'السلة',
    emptyCart: 'سلتك فارغة',
    addToCart: 'إضافة للسلة',
    total: 'الإجمالي',
    checkout: 'إتمام الشراء',
    searchPlaceholder: 'ابحث عن منتج...',
    noResults: 'لا توجد نتائج تطابق بحثك',
    loginTitle: 'مرحباً بك مجدداً',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    registerTitle: 'إنشاء حساب جديد',
    username: 'اسم المستخدم',
    phoneNumber: 'رقم الهاتف',
    confirmPassword: 'تأكيد كلمة المرور',
    joinNow: 'انضم الآن',
  },
  en: {
    appName: 'SYRIA GAMING HUB',
    home: 'Home',
    shop: 'Shop',
    categories: 'Categories',
    support: 'Support',
    login: 'Login',
    register: 'Register',
    heroTitle: 'Your Digital World in One Place',
    heroSubtitle: 'Accounts, codes, and gifts at best prices with top security.',
    instantDelivery: 'Instant Delivery',
    featuredProducts: 'Featured Products',
    bestSellers: 'Best Sellers',
    browseAll: 'Browse All',
    steamAccounts: 'Steam Accounts',
    steamCodes: 'Steam Codes',
    discordNitro: 'Discord Nitro',
    digitalGames: 'Digital Games',
    safetyFirst: 'Safety First',
    trustedMarketplace: 'Trusted marketplace for all your needs.',
    cart: 'Cart',
    emptyCart: 'Your cart is empty',
    addToCart: 'Add to Cart',
    total: 'Total',
    checkout: 'Checkout',
    searchPlaceholder: 'Search products...',
    noResults: 'No products match your search',
    loginTitle: 'Welcome Back',
    email: 'Email Address',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    registerTitle: 'Create New Account',
    username: 'Username',
    phoneNumber: 'Phone Number',
    confirmPassword: 'Confirm Password',
    joinNow: 'Join Now',
  }
};

export interface Country {
  code: string;
  name: string;
  flag: string;
  dialCode: string;
}

export const COUNTRIES: Country[] = [
  { code: 'SY', name: 'Syria', flag: '🇸🇾', dialCode: '+963' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', dialCode: '+966' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', dialCode: '+971' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', dialCode: '+20' },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', dialCode: '+90' },
  { code: 'US', name: 'United States', flag: '🇺🇸', dialCode: '+1' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', dialCode: '+44' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', dialCode: '+49' },
  { code: 'FR', name: 'France', flag: '🇫🇷', dialCode: '+33' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', dialCode: '+39' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', dialCode: '+965' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', dialCode: '+974' },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴', dialCode: '+962' },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧', dialCode: '+961' },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶', dialCode: '+964' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', dialCode: '+968' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', dialCode: '+973' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾', dialCode: '+218' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', dialCode: '+970' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', dialCode: '+213' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', dialCode: '+212' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', dialCode: '+216' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩', dialCode: '+249' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪', dialCode: '+967' },
];

export const SAMPLE_PRODUCTS = [
  {
    id: '1',
    name: 'Steam Account - CS2 Prime + 50 Games',
    category: Category.STEAM_ACCOUNT,
    price: 45.00,
    description: 'High level account with CS2 Prime status and many AAA titles including Elden Ring and Sekiro.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=400',
    badge: 'Trending',
    deliveryType: 'escrow',
    rating: 4.8,
    reviewsCount: 124,
  },
  {
    id: '2',
    name: '$50 Steam Gift Card (Global)',
    category: Category.STEAM_CODE,
    price: 52.50,
    description: 'Instant delivery Steam wallet code valid for all regions. No activation issues.',
    image: 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&q=80&w=400',
    badge: 'Instant',
    deliveryType: 'instant',
    rating: 5.0,
    reviewsCount: 542,
  },
  {
    id: '3',
    name: 'Discord Nitro - 1 Year Subscription',
    category: Category.DISCORD_GIFT,
    price: 89.99,
    description: 'Full Nitro subscription with 2 server boosts, HD streaming, and custom icons.',
    image: 'https://images.unsplash.com/photo-1620332372374-f108c53d2e03?auto=format&fit=crop&q=80&w=400',
    badge: 'Best Deal',
    deliveryType: 'instant',
    rating: 4.9,
    reviewsCount: 890,
  },
  {
    id: '4',
    name: 'Valorant Points - 5000 VP (EU)',
    category: Category.STEAM_CODE,
    price: 49.99,
    description: 'Unlock agents and premium skins instantly in Valorant EU region.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=400',
    badge: 'New',
    deliveryType: 'instant',
    rating: 4.7,
    reviewsCount: 231,
  },
  {
    id: '5',
    name: 'GTA V Online Modded Account',
    category: Category.STEAM_ACCOUNT,
    price: 25.00,
    description: 'Fresh account with $500M and level 120. All unlocks completed.',
    image: 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&q=80&w=400',
    deliveryType: 'escrow',
    rating: 4.5,
    reviewsCount: 98,
  },
  {
    id: '6',
    name: 'Cyberpunk 2077 - Digital Key',
    category: Category.DIGITAL_GAME,
    price: 35.00,
    description: 'Official GOG global key for the Ultimate Edition of Cyberpunk 2077.',
    image: 'https://images.unsplash.com/photo-1605898399783-186678b8f970?auto=format&fit=crop&q=80&w=400',
    deliveryType: 'instant',
    rating: 4.8,
    reviewsCount: 156,
  }
];
